### ISSUE TITLE
Background image being distorted on pages

### ISSUE THREAD

**Issue by mgifford** [arkadianriver/arkadianriver.com#21]
It is fine in the landing page, but with the reduced size of the header image, I can't see how in the css/main.scss why you would want this: 
`background-attachment: fixed;`

It totally distorted the image.

**Comment by arkadianriver** [comment]
First of all, congratulations! 👰 🤵 :)
About the images, yeah, those header images are intended to be large desktop-sized images that scale down responsively for mobile.. and only really as background texture rather than a clear picture of two lovely people enjoying life. :) So, yeah, their attachment is fixed so that they don't move when the page scrolls up and down and with a `background-size: cover` so that they always stretch to the size of the window width. If I understand what you're saying about distortion, you mean resolution when sized larger, right? ..but it looks like you already might have found some large images to avoid that, where the `image` page value is used on the front page whereas the `background-image` is used for the page's header.. so you can use a different pic as the background. If you'd rather show you two on each page in a smaller pic with higher resolution, what you could do is embed the pic of you two within the page rather than in the header. In fact, if you do embed the pictures of you in the body, you could specify `options: minihead` in your page headers so that you get just titles with no background image. If you notice also, the header image is dimmed a bit so that the white text stands out and you might not want that. But, anyway, whatever you did, your site looks good to me right now. :)

**Comment by mgifford** [comment]
Thanks Gary. 

I'm not a designer. That said, I do know a thing or two about the web, so I'll put putting forward some other issues in the future. I like to give back by making the libraries I use better where I can.

I haven't played with background-attachment or background-size so thanks. That makes sense. Thanks for exploring some other options. I tried varying the images and didn't find the right mix. I kept getting mostly forehead shots.  That said, I think there's a solution that is working out ok now.

I've got more questions about Jekyll options.  I guess you put that in the Front Matter or _config.yml file.

**Comment by arkadianriver** [comment]
Yeah the options goes in the front matter. If you download another copy of my repo locally and run `jekyll serve --future` on it you'll find a formatted version of this topic, which is the "documentation" for the repo: https://github.com/arkadianriver/arkadianriver.com/blob/master/_posts/3016-02-26-template.md Most of the options are designed for posts, but that minihead one applies to pages too.

**Comment by mgifford** [comment]
Cool. Thanks for putting that together.
