### ISSUE TITLE
Each page should have an H1

### ISSUE THREAD

**Issue by mgifford** [arkadianriver/arkadianriver.com#22]
This should help with SEO & accessibility. 

These are in both:
  _includes/header-inner.html
  _layouts/landing.html

Which means we also need to modify: 
  modified:   css/main.scss

I tried to do a PR here but it didn't quite work. Not sure why.
https://github.com/arkadianriver/arkadianriver.com/commit/0af68aa09b4bea2273b2902f52a2501faf74c44c

**Comment by mgifford** [comment]
This also fixes an accessibility issue on all pages as the page language wasn't set https://github.com/arkadianriver/arkadianriver.com/commit/1efe23cc15e59972fc77bec38976086fccbffdbf

**Comment by mgifford** [comment]
and also this one https://github.com/arkadianriver/arkadianriver.com/commit/dfefb7fccfdb54ae0c0cd9d9e532fa66c3007934

**Comment by arkadianriver** [comment]
ah thanks, I'll look through your commits. I can't merge the pull request because it has lots of your wedding stuff in it. But, I'll close it (essentially canceling it). Right now you might notice that any change you make to your master branch goes into this request. Typically when contributing to an upstream repo you want to isolate your changes in a separate branch so that you can continue to work on your own stuff separately. Regardless, thanks so much for the accessibility contributions!

**Comment by mgifford** [comment]
Sorry..  I'll try to pull out the wedding stuff. Happy to make some suggestions that might help others. So much depends on the defaults that people download. Thanks for looking over the suggestions.
