### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by vavrines** [arkadianriver/arkadianriver.com#32]
Hi @arkadianriver 
Google analytics seems not working. The UA tracking ID has been written into `_data/tokens.yml`.
Not yet sure what causes the failure, but it seems [here](https://github.com/arkadianriver/arkadianriver.com/blob/4a808917cdc22befeeaa603b9d1544194ee733fb/_includes/scripts.html#L24) is the only function related with google analytics?

**Comment by arkadianriver** [comment]
Thanks, I need to update it to use the new gtag instead of Analytics. I will test and update it soon.
https://support.google.com/analytics/answer/1008080
And, I should probably exclude that section if a tracking ID is not provided.

But I believe Analytics should still work as is if you have obtained a Tracking ID with Google. Did you do that?

**Comment by arkadianriver** [comment]
Oh, I see, you left the angle brackets around your tracking ID. Remove those and it should work. (But I'll still update it.)
I wish I knew of a better way to indicate variable values in text files than with angle brackets. 😊 
```
google-analytics: UA-n...-m
```

**Comment by vavrines** [comment]
> Oh, I see, you left the angle brackets around your tracking ID. Remove those and it should work. (But I'll still update it.)
> I wish I knew of a better way to indicate variable values in text files than with angle brackets. 
> 
> ```
> google-analytics: UA-n...-m
> ```

I removed the angle brackets and now it works indeed.
Thanks! :)
